### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by pfightingirish** [akeaswaran/cfc-bugs#110]
Thank you for creating this great game.

as I have started to play, I have come up with some suggestions that I believe could help make this game even better (if that is even possible):
1. Could you please add sacks as stats tracked for cornerbacks and safeties? Similarly, please add interceptions as stats tracked for linebackers.
2. Could you please add offensive line rankings? I understand the engine doesn’t allow for stats by offensive lineman (the individual) but what about for the line itself? Sacks given up and average yards per carry maybe?
3. Is there any way to make the buttons to call a play (while in game) show up on the same screen? As it is currently, you need to scroll right or down to get to some of the plays.
4. Would LOVE in season recruiting and/or recruit scouting. 

Thank you again for all of your work on this amazing game!

**Comment by akeaswaran** [comment]
> 1. Could you please add sacks as stats tracked for cornerbacks and safeties? Similarly, please add interceptions as stats tracked for linebackers.

The stats you've mentioned are tracked for those respective positions, but they're not listed in the box score because of space constraints on smaller screens. I have an item in my backlog to take another look at adding stats programmatically to support more stats on larger screens, but I don't know when I'll get to that.

> 2. Could you please add offensive line rankings? I understand the engine doesn’t allow for stats by offensive lineman (the individual) but what about for the line itself? Sacks given up and average yards per carry maybe?

Sure, I can do that. 

> 3.Is there any way to make the buttons to call a play (while in game) show up on the same screen? As it is currently, you need to scroll right or down to get to some of the plays.

This is kinda by design -- on a phone screen, there's not a lot of space to display the play art and the relevant text. I'm not sure there's a cleaner way to handle this; every way I can think of designing this would require the user to scroll in some way.

> 4. Would LOVE in season recruiting and/or recruit scouting.

I'm considering this for a future release (note: this isn't a promise that it will actually appear; it's just a promise that I will consider it).

Thanks for the feedback!
