### ISSUE TITLE
Coach extending

### ISSUE THREAD

**Issue by LoganNiederbremer** [akeaswaran/cfc-bugs#112]
When i play my first season as a school and 2-10 i lose 2 prestige then the next season i go 6-6 and lose a bowl game then i lose 7 prestige and i cant extend my newly hired head coach cause prestige is to low please fix this that you can sign your head coach and coordinator regardless of the prestige and that if u have a better season than last season you lose less prestige cause it makes no sense

**Comment by akeaswaran** [comment]
> please fix this that you can sign your head coach and coordinator regardless of the prestige

I'm not too keen on this. I don't think you should be able to infinitely extend your head coach if you don't have the program prestige to do so. Why wouldn't a coach look for a new job if he thinks his current one doesn't give him the resources he needs to succeed?

>  if u have a better season than last season you lose less prestige cause it makes no sense

Reposting what I've previously commented on this:

Media predictions generally do dictate how your performance is judged at the end of the season, but the projected number of wins isn’t the important part of the prediction — it’s the “bracket” of teams you’re projected to be in (championship contenders, conference contenders, bowl contenders, etc). In general, the process looks something like this in the average season, using Georgia Tech’s current form as an example:

 1. Teams are all ranked at the beginning of the season to determine projections. Rankings are determined by a combination of team strength ratings and prestige. Tech is projected to finish in the middle or bottom of the conference.
 2. Tech plays through the season and makes a bowl game.
 3. Teams are reranked at the end of the season to determine performance prestige bonuses.
 4. Because Tech is lower-tier but made a bowl game, they are ranked higher than similar-prestige programs that did not make the postseason and are awarded prestige points accordingly.

The projected number of wins is frequently misleading, and it’s something I’m looking at tweaking in a future update. It’s not supposed to be that hard to gain prestige points, even on the Hard difficulty.

**Comment by LoganNiederbremer** [comment]
Okay thank you for explaining why it is like that. Love you game been playing it for like 3 years it’s probably to long don‘t know how long the game has been out but pretty much at the beginning i started playing it.

Von meinem iPhone gesendet
