### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by dalhoon24** [akeaswaran/cfc-bugs#113]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
I cannot advance the week. I’ve tried playing the game and simming it and the app keeps crashing instead of saving and advancing. 

**To Reproduce**
1. Open App
2. Sim or play game
3. App crashes without saving

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
14.4
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
4.2.8
**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone 11 Pro 
**Jailbroken**: Not jailbroken 

**Reproducible:** it happens every single time I try to advance the week

**Expected behavior**
I expected the app to save my progress after the game and not crash

**Video**
If you really need a video I can screen record one, upload it and link it, but basically the app crashes me back to my phones Home Screen when I try to advance the week to the offseason

**Additional context** it’s the national championship game in the 8th season of career mode on hard with KSI if you need those details

**Comment by akeaswaran** [comment]
I'm not seeing consistent and widespread crashing issues in my crash reporter, unfortunately. There's a few possible reasons I can think of for this based on where/when this is occurring:

1. **Your save file is too big** -- yes, this is a problem, depending on how many seasons you play. iOS applies memory constraints on every app, and in rare circumstances, the system will kill the app while it's saving or loading a save file because of the amount of memory it takes to write/read a large save file. If you (or anyone else reading this) is interested in the technical details here, I can provide some links.

2. **Bad app install** -- I've heard that in some cases a device reboot OR reinstalling the app helps alleviate these issues.

Sorry you're experiencing these issues, and sorry I can't be of more help.
