### ISSUE TITLE
CFC New Feature Suggestion

### ISSUE THREAD

**Issue by ToastBoy2988** [akeaswaran/cfc-bugs#117]
CFC Feature Suggestion

Hi. I have been playing this game for a long time now. I think it’s been like 2 years. But anyway this is my most used app on my phone and it’s the best sports simulator out there in my opinion. I am really happy with the updates and the way the game has progressed from what it was. But their is one feature that I think would be really cool. I think it would be cool if you guys added a thing where you could go in and edit players stats that are on your roster or maybe around the league as a whole. Almost like a god mode type thing. Or have the feature there for optional use where if you want to play the game authentically you can, but if you want to get in and have fun and mess with stats than you can. Or have people pay like $1.99 or $0.99 for people to buy the feature cuz in my opinion this app is worth the money or add the feature in for free.

**Comment by akeaswaran** [comment]
This will not be supported, but setting default player ratings and information will be possible via metadata files in a future release. Put simply: editing player information _before_ a save file is created (since metadata files are used to create save files) _will_ be supported, while editing player information _during_ a save file _will not_ be supported_.
