### ISSUE TITLE
Game feature suggestions

### ISSUE THREAD

**Issue by maniacmechanic** [akeaswaran/cfc-bugs#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.  I’d like to see coordinates be able to leave to taking head coaching positions.  Let’s say you have a excellent coordinator and he leaves for a head coaching job then it makes the game a little more challenging.  Would like to see ability to use more than on running back, receiver, tight end during the season.  Example a blocking tight end on running plays, a third down running back.  Would also like to see in state recruits have their own column and possibly in state recruits don’t take as much recruiting power as out of state recruits.

**Comment by akeaswaran** [comment]
> I’d like to see coordinates be able to leave to taking head coaching positions.

This will be supported in a future release. There are a few bugs preventing the current implementation from working properly.

> Would like to see ability to use more than on running back, receiver, tight end during the season. 

This will not be supported. Playbooks are kept intentionally simple to prevent the game from becoming overly complicated.

> Would also like to see in state recruits have their own column 

More precise recruiting filters are coming in a future release.

> and possibly in state recruits don’t take as much recruiting power as out of state recruits.

This is already the case; in-state recruits start with higher base interest levels because of one of the things factored into interest: how close the program is to the recruit's home state.

Thanks for the feedback!
