### ISSUE TITLE
Projections 

### ISSUE THREAD

**Issue by Magel-Bagel** [akeaswaran/cfc-bugs#13]
One thing I’ve thought about has to do with projections before a season. I’ve seen only 3 possible projections: bottom of the conference, going bowling, and battle for playoff spot. If I am projected to go to a bowl game, I can go 6-7 or 10-3 and either way it will say I performed exactly how the media thought and I gain/lose no prestige. I think a cool feature would be to project a range my team will finish in the final rankings, like 10-25 or even a lot worse like 50-60. It just seems weird that I am projected to go to a bowl game and I finish like top 15 but gain no prestige for it. I understand this is harder to do and makes it huff her chance to lose/gain prestige per season but I think it will be a cool addition.

**Comment by akeaswaran** [comment]
That's effectively how things are done right now -- each projection is actually a range of possible final rankings. It's just simplified to a name when displayed to the user. 

When playing on the harder difficulty, your team's performance is compared against the top of each range, rather than the middle of the range (which is how it's done on the normal difficulty). There have been some complaints here and there about this, but in general, this has seemed to work out well in terms of difficulty. However, I'm open to discussion about this!

**Comment by akeaswaran** [comment]
Closed without response for a month.
