### ISSUE TITLE
Add Ideas love the game 

### ISSUE THREAD

**Issue by que989** [akeaswaran/cfc-bugs#132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
For ever Goal your accomplish you get a different play to add to your playcalling sheet. Allow it to were me can also choose up to atleast 10-15 passing plays and 10-15 running plays to add versatility . I really love the game so I figured id give some advice even though i know it’s bigger than you just adding the stuff in .Make some practice scrimmages so you can see what your defense is like ,  you can even give the players points through out the season week bases, based the practices and the games being played .Allow us to make position changes in players( hate spread offense doesn’t allow you to  have a tight end on the field ) And maybe switching your cornerback could save your team if you have a bad safety . But that might can be replaced if you added a two safety system strong and free . Spring games might not be to bad either . Allow full evaluations on plays to see who really fights better on your roster because maybe you have a guy who is a very high overall but isn’t achieving high stats makes you feel like he isn’t helping the team 
**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for the feedback! Let me respond to each of your suggestions specifically:

> For ever Goal your accomplish you get a different play to add to your playcalling sheet. Allow it to were me can also choose up to atleast 10-15 passing plays and 10-15 running plays to add versatility

I have to add new plays to the game manually, and it's a very laborious process for each one. This is not something I want to engage in unless I see a big ask for it from the community, which I haven't really seen so far. Sorry.

> Make some practice scrimmages so you can see what your defense is like , you can even give the players points through out the season week bases, based the practices and the games being played .... Spring games might not be to bad either .

I am considering some sort of training for a future release (note: this is not a promise that this feature will be in the game in the future -- just a note that I will explore the option).

> Allow full evaluations on plays to see who really fights better on your roster because maybe you have a guy who is a very high overall but isn’t achieving high stats makes you feel like he isn’t helping the team

I'm not sure what you mean here -- you should be able to make these roster decisions based on ratings like football IQ, potential, etc. If you're talking about recruits, I'm exploring a scouting option for a future release (same caveat as above applies).

> Allow us to make position changes in players( hate spread offense doesn’t allow you to have a tight end on the field ) And maybe switching your cornerback could save your team if you have a bad safety . But that might can be replaced if you added a two safety system strong and free

Couple of things here: 

1. I'm not looking at adding more playbooks because of the aforementioned amount of manual work that goes into documenting plays into the format required by the game.
2. I'm not planning on adding positional changes to the game. In [this post](https://www.reddit.com/r/FootballCoach/comments/cgkyna/cfc_40_update/), I laid out the central design principles for the future of the game, and given those tenets, converting recruits to different positions (and, by extension, active players to different positions) seems like a bridge too far in terms of game complexity.
