### ISSUE TITLE
The Draft

### ISSUE THREAD

**Issue by LAlmeida15** [akeaswaran/cfc-bugs#146]
To be honest, I think this game has almost everything needed for a great college football sim. I’ve been playing for 2 years now (I believe) and it never stopped being fun. There is, however, 1 feature I would love to see it added whenever possible and it’s related to the draft.

In college football, the draft is the moment when players see all their efforts rewarded by getting a chance to play in the NFL. Now, it is already present in the game but, in my opinion, it needs a revamp. Some ideas you may or may not like: 

More defensive players drafted early (also less QBs and RBs, like no draft has 9 QBs or 6 RBs in Round 1, but I’be seen it happen in one of my previous saves).

The name of the teams the draft these players, even if fictional, to increase immersion in their career storylines (ex: Houston Red Wings or Tampa Bay Pirates, just to name a few) and maybe give players the opportunity to download the “realistic names” metadata such as it’s possible to do with the college teams.

Scouting Reports would be amazing. We can already see the players height, weigh and overall archetype plus the testing numbers in some drills, but I feel like there could be a more complex system in place. Like, adding pro comparisons (former college players could be used), projection as a pro (Franchise player, Starter, Backup, Special Teamer, etc), Relative Athletic Score (and how this could impact the draft value of a player, and so on.

Another amazing aspect that could be added to this is something I touched one earlier: Draft Value. I could be wrong but I’ve seen that players usually get drafted highly in the game based on production and accolades, but sometimes a big time athlete that barely started is overlooked. In the real Draft, some teams are relentless in trying to find athletes first and think they can teach a specific position later.

I really believe that, for example, if you add 32 ficcional pro teams there should be different process that every teams goes trough to select a player, for example, if a team drafts a QB #1 overall in one year, it’s highly uncommon to draft another QB in the following years and they might have other holes in their roster.

Also, some teams might only draft QBs that are 6ft 4 or higher with A Throwing Power, or maybe some teams only draft speedy WRs or Power RBs. All these things depend mostly on scheme fit and need and this is what mostly impacts the draft strategy’s for them (another thing you could maybe add?)

Anyway, I’m sorry for the huge text but these is one of my favorite games on my phone. I always come back to it when it’s draft season or when the football season starts in real life. I hope I could give you some ideas and let me be clear: This game is already awesome, you did a phenomenal job with it. I’m just trying to help you, in some way, make it even better. Thanks :)

                                                    Luiz Antônio.

**Comment by akeaswaran** [comment]
Before I respond to your feedback specifically: I really appreciate the depth of thought put into this, and I'm sorry I haven't been able to respond sooner. This is a really cool idea and adds a lot of depth to players after they leave the college game.

Unfortunately, since this game focuses specifically on the college football experience, I'm not sure adding the level of complexity this idea begets to the draft feature would be a good idea. While it would be more realistic, there would be a lot of additional data to keep track of (especially re: pro team needs), and some users are already having issues with save file sizes in memory. 

Something like this might be perfect for a pro football version of this game, but unfortunately I do not have the bandwidth to build one of those. Sorry.

Thanks again for the feedback though -- I really, really appreciate it!
