### ISSUE TITLE
Additional Context

### ISSUE THREAD

**Issue by GoBeavs92** [akeaswaran/cfc-bugs#170]
**Additional context**
 
 It would be nice if people who use this app had some more in game options. For example: a trick play or two to use, a kneel option, spike the ball( to stop clock), etc. Also, some additional information to give your offense/defense before you send in the play: EX; throw the ball deep! When you have very little time and you need a score within one play or make sure to get out of bounds to stop the clock!

I have a lot of ideas and I’m a former HS football coach if you need specifics?

Regards,
Steve Madore

**Comment by akeaswaran** [comment]
I totally understand where you're coming from with this feedback, but the game simulation is meant to be simple. There's no play-clock or running clock on plays, so there's no need for timeouts or specific in-play "advice" to head for the sideline because the game-clock is frozen between downs to allow users to select their plays. While these options would produce a more realistic simulation, building them out would add a lot more complexity to the game, and given that I'm nearing the end of active development (with only one major release left on the roadmap), I'm reluctant to add more and more of that to a simulation engine most users seem pretty happy with the current state of.

Hope this clarifies my stance here. Thanks for the feedback!
