### ISSUE TITLE
Hi just a few suggestions for one maybe as a feature called hometown hero where players from the state or especially the town that your colleges and get training boots in the off season. Could you also include offensive schemes with two tight end sets. Also as adding Gatorade player of the year would be nice in scouting points to let us know the durability in the football IQ of a player

### ISSUE THREAD

**Issue by kop77e** [akeaswaran/cfc-bugs#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi just a few suggestions, for one maybe add a feature called hometown hero where players from the state or especially the town that your colleges and get training boosts in the off season. Could you also include offensive schemes with two tight end sets. Also as adding Gatorade player of the year would be nice as well as scouting points to let us know the durability in the football IQ of a player. Finally I would like to see some crazier players they could be labeled in recruiting as Generational and have insane stats coming out of high school I also some diversity in the size of skill players and D linemen maybe sprinkle in a 6’7 tightend or a 6,6 365 D linemen here and there to make it fun. Thanks man.

**Comment by akeaswaran** [comment]
> Could you also include offensive schemes with two tight end sets.

I'm not exploring changes to the playbooks currently in the game at this time. Creating new playbooks or adding new plays is a very time-consuming process that I do not want to invest in unless there is a groundswell of desire for it from the community. Sorry.

> adding Gatorade player of the year
> Finally I would like to see some crazier players they could be labeled in recruiting as Generational and have insane stats coming out of high school

Not really sure these add anything to the game, unfortunately -- they would just be tags on the highest rated player. Generating high school stats would also add a large amount of data to the game, which I am reluctant to do as many people have already reported crashing issues due to large save file sizes. Sorry.

> diversity in the size of skill players and D linemen maybe sprinkle in a 6’7 tightend or a 6,6 365 D linemen

I understand the desire for this, but I'm pretty happy with how heights and weights are generated in the game (IE: based on NFL Combine data) currently. Sorry.
