### ISSUE TITLE
Enhanced Options

### ISSUE THREAD

**Issue by domdaddy1230** [akeaswaran/cfc-bugs#189]
I'd love to be able to move teams between conferences, edit players on the fly, be able to make new rivals, maybe even change the amount of the teams in the playoffs. More freedom for the player to make the simulation more of a sandbox in addition to what's already in place. 

Additionally, the ability to start off as a coordinator and then progress into being a head coach is also intriguing. 

Additionally I personally can't get my recruiting to work in the new update (5.1) even after turning it back on in the settings.

**Comment by akeaswaran** [comment]
> Additionally I personally can't get my recruiting to work in the new update (5.1) even after turning it back on in the settings.

Can you please elaborate on this? What do you mean by "my recruiting"? Are you on the latest update (5.1.2)? What exactly is the problem you are experiencing?

> Additionally, the ability to start off as a coordinator and then progress into being a head coach is also intriguing.

I originally committed to building this out, but due to some complexities and unforeseen issues in the simulation engine that caused massive amounts of problems in 5.0.x, I had to shelve those plans. Sorry.

> I'd love to be able to move teams between conferences, edit players on the fly, be able to make new rivals, maybe even change the amount of the teams in the playoffs.

Couple of notes here:

1. > edit players on the fly, be able to make new rivals

Both of these things are already supported in the game during offseasons:
- You can edit the information of any player one time from their profile by tapping the edit button in the top right corner (will look like a pad and pencil)
- You can edit rivalries by heading to the Team Streaks page and swiping right-to-left on any team to see rivalry options.

2. >  able to move teams between conferences

I do not have plans to support this beyond promotion/relegation. If you want to set your own conference alignment, I recommend using metadata files.

3. > maybe even change the amount of the teams in the playoffs

This would not be a simple process and as such, I'm waiting until the actual official announcement of an expanded IRL playoff (the rumors over the last year do not count) to do this work. Many game processes rely on a standard number of game weeks and making that adjustable is risky. 

Thanks for the feedback!

**Comment by domdaddy1230** [comment]
sorry for the lack of clarity. When I start a new save file I am having trouble getting my recruitment screen. Where it usually is is replaced by a search feature where I can quickly look up teams. I went to the settings to see if anything had changed and I saw that I could turn on/off recruiting if I wanted to but no matter what I have it set to I still cant get it to come back. This happened both in new school and career modes that I made. perplexing.

**Comment by akeaswaran** [comment]
Ok, I see. Recruiting hasn't disappeared, but there's no option to turn on/off recruiting in the Settings panel (just swipe actions, which are not the same thing). As of 5.1, new save files can not enable in-season recruiting due to issues with data storage and as well as user feedback. Pre-existing save files that already have the feature enabled can still continue using it. Recruiting is still available during the offseason as it always is.

I am still evaluating if in-season recruiting will return, and I will update the community as soon as I make a decision.
