### ISSUE TITLE
Recruiting: No Defensive Players

### ISSUE THREAD

**Issue by Static9K** [akeaswaran/cfc-bugs#191]
Each recruiting year, no defensive players are populating as available recruits. This is has been validated by clearing all of the filters and running multiple seasons - no defensive players populate in any season. 

iOS Version: 15.0.1
CFC Version: 5.1.3
iPhone 12 Pro
Not Jailbroken
Career / Hard / No Coaching / Relegation On / Automated Recruiting Off

This bug is reproducible every time. 

Expected behavior: defensive players are available to recruit.

**Comment by akeaswaran** [comment]
Not sure this is a bug: the chances of no team needing defensive players year-over-year is infinitesimal, and this issue has typically come up due to not selecting archetypes for defensive positions. 

However, if you _have_ selected archetypes for defensive positions you've selected and players still aren't showing up, please let me know and I'll take a look.
