### ISSUE TITLE
Recruiting 

### ISSUE THREAD

**Issue by buechler17** [akeaswaran/cfc-bugs#202]
Bring back in season recruiting as well as make it more in depth

**Comment by akeaswaran** [comment]
The option to start new save files with in-season recruiting was disabled in 5.1 primarily due to crashing issues that are a result of data storage overhead created by the mode. Existing save files that already had the feature enabled can continue to use it, but further creation has been stopped for now.

It’s on my list to do some due diligence work on my end to track down where those issues are and how to deal with them, but without those answers, it’s unclear at this time if/when the feature will return.
