### ISSUE TITLE
Some Improvement ideas

### ISSUE THREAD

**Issue by CatoBlack** [akeaswaran/cfc-bugs#207]
**Is your feature request related to a problem? Please describe.**
Me and a few of the guys I work with all play this game and we all got together and came up with a few ideas.

**Describe the solution you'd like**

For starter, we all are a little frustrated with the game play when it comes to the actual games, perhaps a merging between the gamecast and the physical gameplay to make the experience more realistic. It would just be great to be able to watch my coordinators but also try to call a play myself when I’m disappointed with their performances like a real head coach.
   Another suggestion would be the ability to improve players between games or have stat improvements and reversions due to gameplay along with the ability to sub players in order to give non starters playing time to improve or boost the impact on their overall.
   I also wondered if there could be a better more in depth way of customization. I understand it’s impossible for the game to be 100% accurate for teams and conferences, however some of us would like the ability to make our save files more realistic. I’ve done so as best I could but ran into a few issues. I’d like the ability to add team numbers or remove them along with conferences.
   And lastly perhaps the ability to improve your team with practicing between weeks and during the off season, with the added potential of injuries similar to games. And to counter the decision offer the option of breaks And have morale l be the repercussion for too much practice. Which could act as a performance booster/reduction.

**Additional context**
I know all this is a bit much but they were just some ideas I had.

**Comment by akeaswaran** [comment]
> the ability to sub players in order to give non starters playing time to improve

This would go against a major game design tenet (as listed [here](https://www.reddit.com/r/FootballCoach/comments/cgkyna/cfc_40_update/)), and as such, I will not be incorporating it. Sorry.

> I also wondered if there could be a better more in depth way of customization. I understand it’s impossible for the game to be 100% accurate for teams and conferences, however some of us would like the ability to make our save files more realistic. I’ve done so as best I could but ran into a few issues. I’d like the ability to add team numbers or remove them along with conferences.

I think most of what people want can be done via metadata file, but the number of teams per conference will not be changing. Handling situations with more/fewer than 10 teams in a conference would require added complexity in the scheduling algorithm, and it would require overhauling a lot of underpinnings inside save files. Sorry.

I really appreciate all of the feedback and ideas, but my goal is to keep the game pretty simple. I don't want to weigh players down with a lot of buttons or knobs to mess with in order to do well. Hope this makes sense!
