### ISSUE TITLE
Ability to go back to last save file

### ISSUE THREAD

**Issue by chicagobear** [akeaswaran/cfc-bugs#22]
It is always frustrating when I get the message that says corrupt save file. Lately it seems every time I exit the app, even when I’m not simulating through the season, it becomes corrupt. I think if you could go back to your last save that would be great. Even if you had to go back a year or something that would be better than the current situation. Also if you could add Offensive and Defensive coordinations that would be great. I love the game though and especially the latest updates!

**Comment by akeaswaran** [comment]
There looks to be a bug in the current update that causes this save file issue. It's not actually corrupted -- player population in recruiting was not adjusted properly. A fix to this will roll out with the next update.

To respond directly to your "last save file" idea: this isn't necessarily possible since the game doesn't store "save states" like many actual video games do -- it simply writes to and reads from a single file, so if there's something wrong with the file because of a user action, there's no way for me to know 1) what user action took place to corrupt the file and therefore 2) how to adjust the file to fix whatever was corrupted. 

Offensive/Defensive Coordinators are under consideration for a future release (but no promises on if/when that'll be). 

Thanks for the feedback and suggestions!

**Comment by akeaswaran** [comment]
4.1.5+ should have properly fixed this save corruption issue.
