### ISSUE TITLE
Additional Formation Settings

### ISSUE THREAD

**Issue by ItsJustRyann3** [akeaswaran/cfc-bugs#226]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I’d like a way to split carries between running backs without having to go to a smash mouth playbook that gives my rbs 45 carries and my qb only 15 passes. 

**Describe alternatives you've considered**
A fix that I feel would work very well is replacing the roster tab with a “coaching” tab where you could set a rotation for your position players as well as edit the depth chart. Maybe a slider where you could set a % of snaps you want each player taking. 

**Additional context**

**Comment by akeaswaran** [comment]
Reordering depth charts is already supported: just tap the icon in the top right of the Depth Chart tab and select "Edit Depth Chart". That will allow you to reorder players on the depth chart. Once you're done, hit "Done" in the top right corner of the screen to save your changes. 

Unfortunately, I will not be supporting player rotation and backups in each game. I want to keep the game simple and avoid having users turn a bunch of knobs and press a bunch of buttons in order to be successful. If the community comes back and says "we really, really want more adjustments to in-game coaching strategy and player use", I'll take another look at it, but so far, I haven't seen a massive groundswell of desire for it. Sorry.
