### ISSUE TITLE
IDEAS

### ISSUE THREAD

**Issue by HunterXVI** [akeaswaran/cfc-bugs#233]
- **Is your feature request related to a problem? Please describe.** (THE BOX SCORE IS COOL AND ALL BUT IT WOUKD BE AWESOME IF WE COUKD GET HOW. MANY POINTS WE SCORED A QUARTER JUST TO SEE IF WE MADE A HUGE COMEBACK OR SOMETHING WHEN I PRESS THE SCORE TO GET THE STATS IT SHOULD BE UNDER ALL THE PLAYER STATS AFTER EACH GAME)

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] ( IM FRUSTRATED WHEN I GET SOMEONE GOOD FROM RECRUITING AND I CANT START THEM BC SOMEONE ELSES OVERALL IS BETTER SO I HAVE TO WAIT 2 YEARS AND I WISH EVERYONE GOT TO START OR YOU CAN CHOSE TO PLAY A BACKUP FOR A CERTAIN AMOUNT OF TIME LIKE 4th QUARTER OR EVEN HALF A GAME I HATE SEEING MY PLAYERS GO TO WASTE FOR 2 YEARS) 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. ( BOX SCORE FOR POINTS A QUARTER AND THE ABILITY TO START BACKUPS OR LET THEM PLAY IN EACH GAME OR SOMETHING LIKE THAT SO THEY DONT ROTTEN ON THE BENCH.)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. ( TO INVEST PRESTIGE POINTS INTO A CHARACTER NOT LIKE RECRUITING THEM BUT KINDA TO GET TO KNOW THE PLAYER FOR A BETTER CHANCE AT GETTING THEM) ( PRESENTING PLAYER DEALS FOR MONEY AND SEEING THE CONTRACTS OF COACHES AND ETC… 

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for the feedback! Let me hit your points individually:

1. Quarter box scores: I haven't been able to implement this in a way that I like just yet, so it's been put on the back burner for now. It may make it into a future release.
2. Reordering depth charts to let lower overall players start: this is already supported -- just tap the icon in the top right of the Depth Chart tab and select "Edit Depth Chart". That will allow you to reorder players on the depth chart. Once you're done, hit "Done" in the top right corner of the screen to save your changes. I will not be supporting player rotation and backups in each game -- sorry.
3. Investing points in players: I'm not really sure what you mean by this. What you've presented sounds exactly like using points to recruit players. 
4. NIL deals for players: I haven't really thought about this honestly, but a recruiting option for this may make it into a future release.
5. Contracts for coaches: while it would be nice to attach monetary values to a bunch of things in game, Apple had issues with my use of the word "dollars" and related iconography instead of points in a previous release. I will probably not be adding contract values (or NIL deal values, if that option is integrated) for this reason. Sorry.
