### ISSUE TITLE
Records

### ISSUE THREAD

**Issue by King-0f-Blades** [akeaswaran/cfc-bugs#234]
I have a few suggestions, one being in the records section, each record needs a label as to what the record is, I.e. in the career tab the running back records would have Rush TDs written on it as well as Rush Yards etc to better tell which record is what. Currently you have to examine their stats to figure out what the record is.

My second suggestion is to implement an ability to create custom teams, and upload the roster so that others can play it, or use the teams you’ve created.

Third the recruiting could use some more features so it doesn’t feel so stagnant, it doesn’t feel like there is actual recruiting battles going on during the season. And doesn’t seem like there’s much to go by to evaluate players, maybe add a way to further scout players, recruiting is the foundation of all dynasty mode games, it needs to be quite interactive and challenging. Gives more depth and storylines to dynasties, like you lose a back and forth recruiting battle with a top QB recruit because of a bad showing during an official visit to a game, ex: you didn’t meet certain goals like pass yards, or pass touchdowns, etc. and he ends up committing to your rival and ends up being a superstar winning POY multiple times and you always sit there and wonder what could have been if you landed that player. I just want more interactive and challenging recruiting that feels a bit more realistic as to how difficult it is to battle for players irl. Maybe consider adding a NIL attraction stat to teams or something.

thanks for considering my ideas. I hope they in some way help improve the game.

**Comment by akeaswaran** [comment]
Thanks for the feedback, but I'm fairly sure all of the items you've mentioned are already supported in-game.


1. Each record in the Records menu  is clearly labeled with what statistic it's associated with and what context it was achieved in (the tab at the top of the screen allows you to choose the context: Game, Season, or Career). Are we talking about the same Records menu? I accessed it via Career tab > Team Records.

2. You can export metadata files from the settings panel with full rosters and customize/share those for others in import. You just have to manage where those files are stored and where they're shared from (iCloud, Dropbox, GitHub, etc) because I don't have the capital to manage a storage solution.

3. This is the one that I'm a bit unsure about. If you enable in-season recruiting for your save file when you start a fresh one, you'll see these recruiting battles happen every so often with updates in your latest headlines feed. I can add a little more depth for scouting insofar as allowing users to cash program points to reveal stats, but otherwise I think I'm happy with how that feature works as this point. If you're not, keep letting me know and I'll take in the feedback to see what I can do.
