### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by jbird477** [akeaswaran/cfc-bugs#26]
It would be really cool if two or three people could coach in the same universe so their teams could play each other.

**Comment by akeaswaran** [comment]
An online dynasty mode like that is tough for a number of reasons, but primarily because it would require a server and other web resources that would have monthly out-of-pocket costs.

I don’t want to say no outright — I think having this would be very cool, but as it stands at this moment, the chances of adding this are very low.

Thank you for the idea though!
