### ISSUE TITLE
Multiple Teams

### ISSUE THREAD

**Issue by BrandonBerkhan** [akeaswaran/cfc-bugs#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hey, my name is Brandon, I’ve been playing since the first version. My request is simple, allow multiple user teams. In two ways. Allow one user to run multiple teams on one play through. And two, create a way to allow two (or a couple more) people to play with one another on a play though. Thanks for listening!

**Comment by akeaswaran** [comment]
Thanks for your support! Let me respond to both of your points individually:

1. This would require a big, big overhaul of the simulation engine to support and it would make the game pretty complex. For those reasons, I don't really think that'll work. 
2. Unfortunately, the sort of distributed "franchise mode" that you're describing is tough for a number of reasons, but primarily because it would require a server and other web resources that would have monthly out-of-pocket costs. I don't want to say no outright -- I think it would be super cool -- but as it stands at this moment, the chances of adding this are very low. 

Sorry to be the bearer of bad news, but thank you for the suggestions -- I do appreciate them!
