### ISSUE TITLE
Expanded Playoffs

### ISSUE THREAD

**Issue by gatorfan1** [akeaswaran/cfc-bugs#31]
I would like to make a suggestion for an expanded playoff system, or options to have an expanded playoff system enabled if the player wants standard 4 team PO, or it could be adjusted to top 6, 8, 10, or 12 :) 

Just as an additional option, I love the game as it is but an expanded playoff option could be really fun too :)

**Comment by akeaswaran** [comment]
I have no plans to add an expanded playoff at this time because it would take a pretty significant rewrite of some tricky parts of the game engine. If/When IRL college football moves to expand the playoff, I'll see about prioritizing that work. Thanks for the suggestion though -- I appreciate the feedback!

**Comment by gatorfan1** [comment]
Ahhh I understand! :) I just wanted to make a suggestion for a game that i
very much appreciate! Thank you so much for making such an awesome game, I
have played this almost since you first released it and I love how the game
has improved and changed! Keep it up! And thank you for taking the time to
respond to me! Do you have any plans for future changes at this time? :)

**Comment by akeaswaran** [comment]
There's a few more updates with new feature planned, but my plans are not concrete yet and work hasn't started on the next update just yet. Once I have something to share with the community, I will!
