### ISSUE TITLE
Issues with top 25 rankings 

### ISSUE THREAD

**Issue by chrishillyard1219** [akeaswaran/cfc-bugs#33]
Please fill out the template below to make sure I can assist you most effectively.

I hadn’t lost a game in 5 years. Then went 13-0 two years in a row and was ranked #5 and missed the playoff despite teams ranked ahead of me having losses.

**Comment by akeaswaran** [comment]
There were some issues around this prior to 4.1.7 because of a typo in the poll voting formula. This was corrected in 4.1.7.

If you're on 4.1.7 and still seeing this, strength of wins matters _a lot_ to the ranking formula and the game doesn't really have the concept of "poll inertia" (where voters continue to rank a team highly because of reputation or previous performances) built in, so even if you do go undefeated five years in a row, only the performances in the current season affect your poll ranking.
