### ISSUE TITLE
8 team playoff

### ISSUE THREAD

**Issue by jegrossman** [akeaswaran/cfc-bugs#35]
**Is your feature request related to a problem? Please describe.**
Im always frustrated when i am the 5th or 6th team in the ranking despite going undefeated or having 1 close loss OOC

**Describe the solution you'd like**
The option to expand the playoff from 4 teams to 8 teams

**Describe alternatives you've considered**
I don’t think there are really alternatives to this 

**Additional context**

**Comment by akeaswaran** [comment]
I have no plans to add an expanded playoff at this time because it would take a pretty significant rewrite of some tricky parts of the game engine. If/When IRL college football moves to expand the playoff, I'll see about prioritizing that work. Thanks for the suggestion though -- I appreciate the feedback!
