### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by 22goforit** [akeaswaran/cfc-bugs#44]
**Describe the bug**
May not be a bug. The option for plat calling a game doesn’t appear. Nor does the option to watch the game cast of a game. The only option I see is to simulate the game. 

**To Reproduce**

**iOS version**:
4.1.9

**CFC version**
(1)

**iOS device**
iPhone 8

**Jailbroken**
No

**Reproducible:**
Yes. In that it never appears. 

**Expected behavior**
I expected to click on the “play week” tab and see options to simulate game, watch game cast, and to play call. 

**Screenshots**
![464F450F-A3A7-4645-B245-4455639DCB9C](https://user-images.githubusercontent.com/69737815/90323702-bf9aef80-df19-11ea-9e02-a1d80f42af69.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
If you're on any iPhone with a 4-inch screen OR you have [Display Zoom enabled](https://support.apple.com/guide/iphone/magnify-the-screen-iphd6804774e/ios) (which mimics the 4-inch screen size), you won't see those options. Due to layout constraints, those features are only available on the larger displays.
