### ISSUE TITLE
A simplifies option

### ISSUE THREAD

**Issue by Adamstrecker** [akeaswaran/cfc-bugs#49]
When I first got this game it was simple, easy, and quick to learn. But now with all the new features, I feel like trying to have fun and lead 25 prestige American Samoa to greatness, feels more like a Boring job than a game.
    One feature suggestion, or game option, I would like to offer, would be a simplified version (basically a dI’m bed down version). How I feel this would work is either an option in Settings, or an option after you choose school or career. I feel the new layout of the game is far better than the old version, but I don’t know how well it would work with far less features.
     I think the easiest thing you could do that would probably save a ton of time, is put a button that changes the game back to the old version.

**Comment by akeaswaran** [comment]
> I think the easiest thing you could do that would probably save a ton of time, is put a button that changes the game back to the old version.

In a bit of irony, this is actually not at all possible without a substantial rewrite of the codebase. 

I'm interested to understand why you think the game has become a "boring job" -- you don't _have_ to interact with any of the newer features (play-calling, OOC scheduling, playbook optimizing using archetypes, etc.) if you don't want to. You're always able to ignore all that jazz and continue to sim through games to recruiting (which I assume must also be included in your idea of the "old version", since it hasn't fundamentally changed since v2.0), pick your players, and then continue to next season. The core gameplay loop hasn't really changed in 4+ years; there's just a lot more bells and whistles now.

Would love to hear your feedback on this, so please do reach out!

**Comment by akeaswaran** [comment]
Closing without response.
