### ISSUE TITLE
Preseason Projections do not impact coach performance judgments

### ISSUE THREAD

**Issue by nickthebaer** [akeaswaran/cfc-bugs#57]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
On The hard level of difficulty, the preseason projections don’t seem to impact how the coach’s performance is judged at the end of the season. The screenshots are from the same season. Expectations were 3-9. The team went 8-5. And the result was “bit of a down year” and I lost prestige from the season results. This happens every time I start a new career in hard difficulty. So it makes it nearly impossible to advance.

**To Reproduce**
1. Start a career
2. Choose I’d like a challenge for difficulty
3. Simulate the season

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)  13.7
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom) Latest
**iOS device**: For example iPhone XS, iPad mini, etc. iPhone X
**Jailbroken**: Whether or not your device is jailbroken No
**Reproducible:** Can you reproduce it every time? Or is it random? Reproducible

**Expected behavior**

If I outperform expectations, my prestige should go up.

**Screenshots**
If possible, add screenshots to help show the problem.

![0288CFAA-186E-49FC-84A7-EDA873D2B7BF](https://user-images.githubusercontent.com/71344528/94694932-59203400-0303-11eb-80fe-58669affac19.png)
![01533BDF-11E4-437C-AEFC-5FC829296E93](https://user-images.githubusercontent.com/71344528/94694939-5a516100-0303-11eb-8b1d-b644f2bf3381.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**
``

**Comment by akeaswaran** [comment]
I've actually touched on this [here](https://www.reddit.com/r/FootballCoach/comments/ibhrh0/the_media_said_they_thought_i_was_going_39_i_go/g1vrbcs/). TL;DR: the record is not the important part; it's the bracket of projections (championship contender, conference contender, bowl contender, bottom feeder, etc) that matters. On the Hard difficulty, your program's performance, measured by its final poll rank, is judged against the first-quartile of the ranks in the projection bracket rather than the midpoint. Here's an example of Hard difficulty progression:

* Alabama is projected to be a national championship contender (IE: ranked 1-15ish)
* Alabama finishes ranked 4th.
* The engine compares Alabama's 14th place finish to the first-quartile of their projection range (1 to 15), which is 4.
* Therefore, Alabama is determined to have underperformed.

Contrast that with Normal difficulty progression:

* Alabama is projected to be a national championship contender (IE: ranked 1-15ish)
* Alabama finishes ranked 4th.
* The engine compares Alabama's 14th place finish to the midpoint of their projection range (1 to 15), which is 8.
* Therefore, Alabama is determined to have met or exceeded expectations (obviously exceeded is not necessarily possible since this is the highest bracket of projections, but you get the point).

Anyway, the main point here is that the record calculation is broken, and I think I have a good fix for that in 4.2 (currently in beta). With that in mind, I'm going to mark this as fixed. Let me know if you still see dissonance between performance and projections in future releases. Thanks for the feedback!
