### ISSUE TITLE
Just some features that I believe will make the game better overall is like a player mode where you can be a player n play a season in high school n have a college career, maybe in the future be able to see the route a player ran during the play or the path they took during the path. More plays, d1 d2 and d3 colleges, etc

### ISSUE THREAD

**Issue by boosteddjayy** [akeaswaran/cfc-bugs#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for the feedback!

A player career mode would be an entirely different game -- one that I'm not interested in making, unfortunately.

I'm happy with the size of playbooks right now, but if enough people want to see them expanded, I can work on that. It's actually pretty difficult to add plays, so I only want to do that if people are interested.

I can't add actual university names, regardless of division, due to licensing reasons, and that being said, there's not much change between NCAA divisions anyway (FCS vs FBS divide aside). I encourage you to create a metadata file if you want to use Division 2 or 3 schools in the game.

**Comment by boosteddjayy** [comment]
I didn’t mean adding specific d1 d2 and d3 colleges i meant like adding in
the different divisions and maybe in hard mode you have to work your way up

**Comment by boosteddjayy** [comment]
Just an idea. The game already is pretty good and I enjoy it a lot. One
other feature I would like to maybe see in the future is how your former
players turned out in the pros like if they were a bust or pro hall of fame
bc we can only see when they were drafted.
